// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PicklesDoc.Pickles.DocumentationBuilders.Markdown.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Scenario Steps")]
    public partial class ScenarioStepsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Scenario Steps.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Scenario Steps", "    In order to document the Gherkin steps\r\n    As a reader of the generated docu" +
                    "mentation\r\n    I want the scenario steps to appear in order below the scenario h" +
                    "eading.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Output has simple given step for scenario")]
        public virtual void OutputHasSimpleGivenStepForScenario()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Output has simple given step for scenario", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
    testRunner.Given("I have a feature called \'My Scenario Steps Feature\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
    testRunner.And("I have a scenario called \'Simple Given Step\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Keyword",
                        "Step"});
            table1.AddRow(new string[] {
                        "Given",
                        "I have a simple given step"});
#line 9
    testRunner.And("I have the scenario steps", ((string)(null)), table1, "And ");
#line 13
    testRunner.When("I generate Markdown output", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Content"});
            table2.AddRow(new string[] {
                        "#### Scenario: Simple Given Step"});
            table2.AddRow(new string[] {
                        ">"});
            table2.AddRow(new string[] {
                        "> **Given** I have a simple given step"});
#line 15
    testRunner.Then("the Markdown output has the lines in the following order", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Output has simple given & and step for scenario")]
        public virtual void OutputHasSimpleGivenAndStepForScenario()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Output has simple given & and step for scenario", ((string[])(null)));
#line 22
this.ScenarioSetup(scenarioInfo);
#line 23
    testRunner.Given("I have a feature called \'My Scenario Steps Feature\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 24
    testRunner.And("I have a scenario called \'Multiple Given Steps\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Keyword",
                        "Step"});
            table3.AddRow(new string[] {
                        "Given",
                        "I have a simple given step"});
            table3.AddRow(new string[] {
                        "And",
                        "I have second given"});
#line 25
    testRunner.And("I have the scenario steps", ((string)(null)), table3, "And ");
#line 30
    testRunner.When("I generate Markdown output", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Content"});
            table4.AddRow(new string[] {
                        "#### Scenario: Multiple Given Steps"});
            table4.AddRow(new string[] {
                        ">"});
            table4.AddRow(new string[] {
                        "> **Given** I have a simple given step"});
            table4.AddRow(new string[] {
                        ">"});
            table4.AddRow(new string[] {
                        "> **And** I have second given"});
#line 32
    testRunner.Then("the Markdown output has the lines in the following order", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Output has a step with a table for scenario")]
        public virtual void OutputHasAStepWithATableForScenario()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Output has a step with a table for scenario", ((string[])(null)));
#line 41
this.ScenarioSetup(scenarioInfo);
#line 42
    testRunner.Given("I have a feature called \'My Scenario Steps Feature\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 43
    testRunner.And("I have a scenario called \'Table Given Step\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "TableColA",
                        "TableColb"});
            table5.AddRow(new string[] {
                        "TDA1",
                        "TDB1"});
            table5.AddRow(new string[] {
                        "TDA2",
                        "TDB2"});
#line 44
    testRunner.And("I have the scenario step with table \'Given I have a table\'", ((string)(null)), table5, "And ");
#line 49
    testRunner.When("I generate Markdown output", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Content"});
            table6.AddRow(new string[] {
                        "#### Scenario: Table Given Step"});
            table6.AddRow(new string[] {
                        ">"});
            table6.AddRow(new string[] {
                        "> **Given** I have a table"});
            table6.AddRow(new string[] {
                        ">"});
            table6.AddRow(new string[] {
                        "> | TableColA | TableColb |"});
            table6.AddRow(new string[] {
                        "> | --- | --- |"});
            table6.AddRow(new string[] {
                        "> | TDA1 | TDB1 |"});
            table6.AddRow(new string[] {
                        "> | TDA2 | TDB2 |"});
#line 51
    testRunner.Then("the Markdown output has the lines in the following order", ((string)(null)), table6, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
