// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("Pickles")]
[assembly: AssemblyCompanyAttribute("Pickles")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Jeffrey Cameron 2010-2012, PicklesDoc 2012-present")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("2.6.3")]
[assembly: AssemblyFileVersionAttribute("2.6.3")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.6.3";
        internal const string InformationalVersion = "2.6.3";
    }
}
