// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("Pickles")]
[assembly: AssemblyCompanyAttribute("Pickles")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Jeffrey Cameron 2010-2012, PicklesDoc 2012-present")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("2.13.0")]
[assembly: AssemblyFileVersionAttribute("2.13.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "Pickles";
        internal const System.String AssemblyCompany = "Pickles";
        internal const System.String AssemblyCopyright = "Copyright (c) Jeffrey Cameron 2010-2012, PicklesDoc 2012-present";
        internal const System.String AssemblyTrademark = "";
        internal const System.String AssemblyCulture = "";
        internal const System.Boolean ComVisible = false;
        internal const System.String AssemblyVersion = "2.13.0";
        internal const System.String AssemblyFileVersion = "2.13.0";
    }
}
