// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("Pickles")]
[assembly: AssemblyCompanyAttribute("Pickles")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Jeffrey Cameron 2010-2012, PicklesDoc 2012-2013")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("0.18.0")]
[assembly: AssemblyFileVersionAttribute("0.18.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.18.0";
    }
}
