// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.239
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Pickles.Example.xUnit.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class TrigonometryFeature : Xunit.IUseFixture<TrigonometryFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Trigonometry.feature"
#line hidden
        
        public TrigonometryFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Trigonometry", "In order to avoid perform more advanced calculations\r\nAs a math idiot\r\nI want to " +
                    "be able to use trigonometric functions", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(TrigonometryFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Trigonometry")]
        [Xunit.TraitAttribute("Description", "Sine")]
        public virtual void Sine()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sine", new string[] {
                        "trigonometric",
                        "fast"});
#line 7
 this.ScenarioSetup(scenarioInfo);
#line 8
  testRunner.Given("I have entered 90 into the calculator");
#line 9
  testRunner.When("I press sin");
#line 10
  testRunner.Then("the result should be 1 on the screen");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Trigonometry")]
        [Xunit.TraitAttribute("Description", "Cosine")]
        public virtual void Cosine()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cosine", new string[] {
                        "trigonometric",
                        "fast"});
#line 13
 this.ScenarioSetup(scenarioInfo);
#line 14
  testRunner.Given("I have entered 0 into the calculator");
#line 15
  testRunner.When("I press cos");
#line 16
  testRunner.Then("the result should be 1 on the screen");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Trigonometry")]
        [Xunit.TraitAttribute("Description", "Tangent")]
        public virtual void Tangent()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Tangent", new string[] {
                        "trigonometric",
                        "fast"});
#line 19
 this.ScenarioSetup(scenarioInfo);
#line 20
  testRunner.Given("I have entered 45 into the calculator");
#line 21
  testRunner.When("I press tan");
#line 22
  testRunner.Then("the result should be 1 on the screen");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                TrigonometryFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                TrigonometryFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
