Feature: The test runner is not (very) important
	In order to show that the test runner is just for the autogenerated stuff in SpecFlow  
	As a SpecFlow evanglist  
	I want to be able to call my steps in the same manner inspite of the testrunner configured

Scenario: A couple of simple steps
	Given I have step defintions in place
	When I call a step
	Then the step should have been called 