// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecRun
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Scenario Outlines", Description="Here we demonstrate how we deal with scenario outlines", SourceFile="ScenarioOutlines.feature", SourceLine=0)]
    public partial class ScenarioOutlinesFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ScenarioOutlines.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Scenario Outlines", "Here we demonstrate how we deal with scenario outlines", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void ThisIsAScenarioOutlineWhereAllScenariosPass(string result, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("This is a scenario outline where all scenarios pass", exampleTags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 8
  testRunner.Then(string.Format("the scenario will \'{0}\'", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("This is a scenario outline where all scenarios pass, pass_1", Description="\r\nThis means the entire scenario outline passes.", SourceLine=11)]
        public virtual void ThisIsAScenarioOutlineWhereAllScenariosPass_Pass_1()
        {
            this.ThisIsAScenarioOutlineWhereAllScenariosPass("pass_1", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("This is a scenario outline where all scenarios pass, pass_2", Description="\r\nThis means the entire scenario outline passes.", SourceLine=12)]
        public virtual void ThisIsAScenarioOutlineWhereAllScenariosPass_Pass_2()
        {
            this.ThisIsAScenarioOutlineWhereAllScenariosPass("pass_2", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("This is a scenario outline where all scenarios pass, pass_3", Description="\r\nThis means the entire scenario outline passes.", SourceLine=13)]
        public virtual void ThisIsAScenarioOutlineWhereAllScenariosPass_Pass_3()
        {
            this.ThisIsAScenarioOutlineWhereAllScenariosPass("pass_3", ((string[])(null)));
        }
        
        public virtual void ThisIsAScenarioOutlineWhereOneScenarioIsInconclusive(string result, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("This is a scenario outline where one scenario is inconclusive", exampleTags);
#line 17
this.ScenarioSetup(scenarioInfo);
#line 21
  testRunner.Then(string.Format("the scenario will \'{0}\'", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("This is a scenario outline where one scenario is inconclusive, pass_1", Description="\r\nThis means the entire scenario outline is inconclusive.", SourceLine=24)]
        public virtual void ThisIsAScenarioOutlineWhereOneScenarioIsInconclusive_Pass_1()
        {
            this.ThisIsAScenarioOutlineWhereOneScenarioIsInconclusive("pass_1", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("This is a scenario outline where one scenario is inconclusive, pass_2", Description="\r\nThis means the entire scenario outline is inconclusive.", SourceLine=25)]
        public virtual void ThisIsAScenarioOutlineWhereOneScenarioIsInconclusive_Pass_2()
        {
            this.ThisIsAScenarioOutlineWhereOneScenarioIsInconclusive("pass_2", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("This is a scenario outline where one scenario is inconclusive, inconclusive_1", Description="\r\nThis means the entire scenario outline is inconclusive.", SourceLine=26)]
        public virtual void ThisIsAScenarioOutlineWhereOneScenarioIsInconclusive_Inconclusive_1()
        {
            this.ThisIsAScenarioOutlineWhereOneScenarioIsInconclusive("inconclusive_1", ((string[])(null)));
        }
        
        public virtual void ThisIsAScenarioOutlineWhereOneScenarioFails(string result, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("This is a scenario outline where one scenario fails", exampleTags);
#line 30
this.ScenarioSetup(scenarioInfo);
#line 34
  testRunner.Then(string.Format("the scenario will \'{0}\'", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("This is a scenario outline where one scenario fails, pass_1", Description="\r\nThis means the entire scenario outline fails.", SourceLine=37)]
        public virtual void ThisIsAScenarioOutlineWhereOneScenarioFails_Pass_1()
        {
            this.ThisIsAScenarioOutlineWhereOneScenarioFails("pass_1", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("This is a scenario outline where one scenario fails, pass_2", Description="\r\nThis means the entire scenario outline fails.", SourceLine=38)]
        public virtual void ThisIsAScenarioOutlineWhereOneScenarioFails_Pass_2()
        {
            this.ThisIsAScenarioOutlineWhereOneScenarioFails("pass_2", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("This is a scenario outline where one scenario fails, fail_1", Description="\r\nThis means the entire scenario outline fails.", SourceLine=39)]
        public virtual void ThisIsAScenarioOutlineWhereOneScenarioFails_Fail_1()
        {
            this.ThisIsAScenarioOutlineWhereOneScenarioFails("fail_1", ((string[])(null)));
        }
        
        public virtual void AndWeCanGoTotallyBonkersWithMultipleExampleSections_(string result, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("And we can go totally bonkers with multiple example sections.", exampleTags);
#line 43
this.ScenarioSetup(scenarioInfo);
#line 45
  testRunner.Then(string.Format("the scenario will \'{0}\'", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("And we can go totally bonkers with multiple example sections., Examples 1, pass_1" +
            "", SourceLine=48)]
        public virtual void AndWeCanGoTotallyBonkersWithMultipleExampleSections__ExampleSet0_Pass_1()
        {
            this.AndWeCanGoTotallyBonkersWithMultipleExampleSections_("pass_1", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("And we can go totally bonkers with multiple example sections., Examples 1, pass_2" +
            "", SourceLine=49)]
        public virtual void AndWeCanGoTotallyBonkersWithMultipleExampleSections__ExampleSet0_Pass_2()
        {
            this.AndWeCanGoTotallyBonkersWithMultipleExampleSections_("pass_2", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("And we can go totally bonkers with multiple example sections., Examples 2, inconc" +
            "lusive_1", SourceLine=53)]
        public virtual void AndWeCanGoTotallyBonkersWithMultipleExampleSections__ExampleSet1_Inconclusive_1()
        {
            this.AndWeCanGoTotallyBonkersWithMultipleExampleSections_("inconclusive_1", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("And we can go totally bonkers with multiple example sections., Examples 2, inconc" +
            "lusive_2", SourceLine=54)]
        public virtual void AndWeCanGoTotallyBonkersWithMultipleExampleSections__ExampleSet1_Inconclusive_2()
        {
            this.AndWeCanGoTotallyBonkersWithMultipleExampleSections_("inconclusive_2", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("And we can go totally bonkers with multiple example sections., Examples 3, fail_1" +
            "", SourceLine=58)]
        public virtual void AndWeCanGoTotallyBonkersWithMultipleExampleSections__ExampleSet2_Fail_1()
        {
            this.AndWeCanGoTotallyBonkersWithMultipleExampleSections_("fail_1", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("And we can go totally bonkers with multiple example sections., Examples 3, fail_2" +
            "", SourceLine=59)]
        public virtual void AndWeCanGoTotallyBonkersWithMultipleExampleSections__ExampleSet2_Fail_2()
        {
            this.AndWeCanGoTotallyBonkersWithMultipleExampleSections_("fail_2", ((string[])(null)));
        }
        
        public virtual void DealCorrectlyWithBackslashesInTheExamples(string filePath, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deal correctly with backslashes in the examples", exampleTags);
#line 63
this.ScenarioSetup(scenarioInfo);
#line 65
  testRunner.When(string.Format("I have backslashes in the value, for example a \'{0}\'", filePath), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal correctly with backslashes in the examples, c:\\Temp\\", SourceLine=68)]
        public virtual void DealCorrectlyWithBackslashesInTheExamples_CTemp()
        {
            this.DealCorrectlyWithBackslashesInTheExamples("c:\\Temp\\", ((string[])(null)));
        }
        
        public virtual void DealCorrectlyWithParenthesisInTheExamples(string overlyDescriptiveField, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deal correctly with parenthesis in the examples", exampleTags);
#line 72
this.ScenarioSetup(scenarioInfo);
#line 74
  testRunner.When(string.Format("I have parenthesis in the value, for example an \'{0}\'", overlyDescriptiveField), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal correctly with parenthesis in the examples, This is a description (and more)" +
            "", SourceLine=77)]
        public virtual void DealCorrectlyWithParenthesisInTheExamples_ThisIsADescriptionAndMore()
        {
            this.DealCorrectlyWithParenthesisInTheExamples("This is a description (and more)", ((string[])(null)));
        }
        
        public virtual void DealCorrectlyWithOverlongExampleValues(string value1, string value2, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deal correctly with overlong example values", exampleTags);
#line 80
 this.ScenarioSetup(scenarioInfo);
#line 82
  testRunner.When("I have a field with value \'<value>\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 83
  testRunner.Then("the scenario will \'pass_1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal correctly with overlong example values, Please enter a valid two letter coun" +
            "try code (e.g. DE)!", SourceLine=86)]
        public virtual void DealCorrectlyWithOverlongExampleValues_PleaseEnterAValidTwoLetterCountryCodeE_G_DE()
        {
            this.DealCorrectlyWithOverlongExampleValues("Please enter a valid two letter country code (e.g. DE)!", "This is just a very very very veery long error message!", ((string[])(null)));
        }
        
        public virtual void DealWithDuplicateValues(string result, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deal with duplicate values", exampleTags);
#line 89
this.ScenarioSetup(scenarioInfo);
#line 90
    testRunner.Then(string.Format("the scenario will \'{0}\'", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with duplicate values, Variant 0", SourceLine=93)]
        public virtual void DealWithDuplicateValues_Variant0()
        {
            this.DealWithDuplicateValues("pass", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with duplicate values, Variant 1", SourceLine=94)]
        public virtual void DealWithDuplicateValues_Variant1()
        {
            this.DealWithDuplicateValues("fail", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with duplicate values, Variant 2", SourceLine=95)]
        public virtual void DealWithDuplicateValues_Variant2()
        {
            this.DealWithDuplicateValues("inconclusive", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with duplicate values, Variant 3", SourceLine=96)]
        public virtual void DealWithDuplicateValues_Variant3()
        {
            this.DealWithDuplicateValues("pass", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with duplicate values, Variant 4", SourceLine=97)]
        public virtual void DealWithDuplicateValues_Variant4()
        {
            this.DealWithDuplicateValues("fail", ((string[])(null)));
        }
        
        public virtual void DealWithMultipleExampleSectionsWithDuplicateValues(string result, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deal with multiple example sections with duplicate values", exampleTags);
#line 100
this.ScenarioSetup(scenarioInfo);
#line 101
    testRunner.Then(string.Format("the scenario will \'{0}\'", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with multiple example sections with duplicate values, Examples 1, Variant 0", SourceLine=104)]
        public virtual void DealWithMultipleExampleSectionsWithDuplicateValues_ExampleSet0_Variant0()
        {
            this.DealWithMultipleExampleSectionsWithDuplicateValues("pass", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with multiple example sections with duplicate values, Examples 1, Variant 1", SourceLine=105)]
        public virtual void DealWithMultipleExampleSectionsWithDuplicateValues_ExampleSet0_Variant1()
        {
            this.DealWithMultipleExampleSectionsWithDuplicateValues("fail", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with multiple example sections with duplicate values, Examples 1, Variant 2", SourceLine=106)]
        public virtual void DealWithMultipleExampleSectionsWithDuplicateValues_ExampleSet0_Variant2()
        {
            this.DealWithMultipleExampleSectionsWithDuplicateValues("pass", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with multiple example sections with duplicate values, Examples 2, Variant 0", SourceLine=110)]
        public virtual void DealWithMultipleExampleSectionsWithDuplicateValues_ExampleSet1_Variant0()
        {
            this.DealWithMultipleExampleSectionsWithDuplicateValues("fail", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with multiple example sections with duplicate values, Examples 2, Variant 1", SourceLine=111)]
        public virtual void DealWithMultipleExampleSectionsWithDuplicateValues_ExampleSet1_Variant1()
        {
            this.DealWithMultipleExampleSectionsWithDuplicateValues("inconclusive", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with multiple example sections with duplicate values, Examples 2, Variant 2", SourceLine=112)]
        public virtual void DealWithMultipleExampleSectionsWithDuplicateValues_ExampleSet1_Variant2()
        {
            this.DealWithMultipleExampleSectionsWithDuplicateValues("fail", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with multiple example sections with duplicate values, Examples 2, Variant 3", SourceLine=113)]
        public virtual void DealWithMultipleExampleSectionsWithDuplicateValues_ExampleSet1_Variant3()
        {
            this.DealWithMultipleExampleSectionsWithDuplicateValues("pass", ((string[])(null)));
        }
        
        public virtual void DealWithMultipleNamedExampleSectionsWithoutDuplicateValues(string result, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deal with multiple named example sections without duplicate values", exampleTags);
#line 116
this.ScenarioSetup(scenarioInfo);
#line 117
    testRunner.Then(string.Format("the scenario will \'{0}\'", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with multiple named example sections without duplicate values, First set, pa" +
            "ss", SourceLine=120)]
        public virtual void DealWithMultipleNamedExampleSectionsWithoutDuplicateValues_FirstSet_Pass()
        {
            this.DealWithMultipleNamedExampleSectionsWithoutDuplicateValues("pass", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with multiple named example sections without duplicate values, First set, fa" +
            "il", SourceLine=121)]
        public virtual void DealWithMultipleNamedExampleSectionsWithoutDuplicateValues_FirstSet_Fail()
        {
            this.DealWithMultipleNamedExampleSectionsWithoutDuplicateValues("fail", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with multiple named example sections without duplicate values, Second set, i" +
            "nconclusive", SourceLine=125)]
        public virtual void DealWithMultipleNamedExampleSectionsWithoutDuplicateValues_SecondSet_Inconclusive()
        {
            this.DealWithMultipleNamedExampleSectionsWithoutDuplicateValues("inconclusive", ((string[])(null)));
        }
        
        public virtual void DealWithMultipleNamedExampleSectionsWithDuplicateValues(string result, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deal with multiple named example sections with duplicate values", exampleTags);
#line 128
this.ScenarioSetup(scenarioInfo);
#line 129
    testRunner.Then(string.Format("the scenario will \'{0}\'", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with multiple named example sections with duplicate values, First set, Varia" +
            "nt 0", SourceLine=132)]
        public virtual void DealWithMultipleNamedExampleSectionsWithDuplicateValues_FirstSet_Variant0()
        {
            this.DealWithMultipleNamedExampleSectionsWithDuplicateValues("pass", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with multiple named example sections with duplicate values, First set, Varia" +
            "nt 1", SourceLine=133)]
        public virtual void DealWithMultipleNamedExampleSectionsWithDuplicateValues_FirstSet_Variant1()
        {
            this.DealWithMultipleNamedExampleSectionsWithDuplicateValues("fail", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with multiple named example sections with duplicate values, First set, Varia" +
            "nt 2", SourceLine=134)]
        public virtual void DealWithMultipleNamedExampleSectionsWithDuplicateValues_FirstSet_Variant2()
        {
            this.DealWithMultipleNamedExampleSectionsWithDuplicateValues("pass", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with multiple named example sections with duplicate values, Second set, Vari" +
            "ant 0", SourceLine=138)]
        public virtual void DealWithMultipleNamedExampleSectionsWithDuplicateValues_SecondSet_Variant0()
        {
            this.DealWithMultipleNamedExampleSectionsWithDuplicateValues("fail", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with multiple named example sections with duplicate values, Second set, Vari" +
            "ant 1", SourceLine=139)]
        public virtual void DealWithMultipleNamedExampleSectionsWithDuplicateValues_SecondSet_Variant1()
        {
            this.DealWithMultipleNamedExampleSectionsWithDuplicateValues("inconclusive", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with multiple named example sections with duplicate values, Second set, Vari" +
            "ant 2", SourceLine=140)]
        public virtual void DealWithMultipleNamedExampleSectionsWithDuplicateValues_SecondSet_Variant2()
        {
            this.DealWithMultipleNamedExampleSectionsWithDuplicateValues("fail", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Deal with multiple named example sections with duplicate values, Second set, Vari" +
            "ant 3", SourceLine=141)]
        public virtual void DealWithMultipleNamedExampleSectionsWithDuplicateValues_SecondSet_Variant3()
        {
            this.DealWithMultipleNamedExampleSectionsWithDuplicateValues("pass", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
