// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.7.1.0
//      SpecFlow Generator Version:1.7.0.0
//      Runtime Version:4.0.30319.237
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Pickles.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.7.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Generate XHTML from a single, simple feature and scenario")]
    public partial class GenerateXHTMLFromASingleSimpleFeatureAndScenarioFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "GenerateHtmlForSingleFile.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Generate XHTML from a single, simple feature and scenario", "In order to generate documentation from feature files that can be distributed to " +
                    "clients\r\nAs a gherkin language user\r\nI want to generate an XHTML files from a se" +
                    "t of feature files that is organized by folder", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generate XHTML from single feature")]
        public virtual void GenerateXHTMLFromSingleFeature()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Generate XHTML from single feature", ((string[])(null)));
#line 6
 this.ScenarioSetup(scenarioInfo);
#line hidden
#line 7
  testRunner.Given("this feature file", "Feature: Test\r\n    In order to do something\r\n    As a user\r\n    I want to run thi" +
                    "s scenario\r\n\r\n    Scenario: A scenario\r\n\t    Given some feature\r\n        When it" +
                    " runs\r\n        Then I should see that this thing happens", ((TechTalk.SpecFlow.Table)(null)));
#line 19
  testRunner.When("I generate documentation");
#line hidden
#line 20
  testRunner.Then("I should see this XHTML file", @"<?xml version=""1.0"" encoding=""UTF-8"" ?>
<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 Strict//EN"" ""http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd""[]>
<html xml:lang=""en"" xmlns=""http://www.w3.org/1999/xhtml"">
	<head>
		<title>Feature: Test</title>
	</head>
	<body>
		<div id=""feature"" class=""feature"">
			<h1>Feature: Test</h1>
				<p>In order to do something</p>
				<p>As a user</p>
				<p>I want to run this scenario</p>
		</div>
		<ul class=""scenarios"">
			<li id=""0"" class=""scenario"">
				<div class=""scenario-heading"">
					<h2>Scenario: A scenario</h2>
					<p></p>
				</div>
				<div class=""steps"">
					<ul>
						<li class=""step""><span class=""keyword"">Given </span>some feature</li>
						<li class=""step""><span class=""keyword"">When </span>it runs</li>
						<li class=""step""><span class=""keyword"">Then </span>I should see that this thing happens</li>
					</ul>
				</div>
			</li>
		</ul>
	</body>
</html>", ((TechTalk.SpecFlow.Table)(null)));
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#endregion
